<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Church Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .navbar {
            background-color: #333;
            overflow: hidden;
            text-align: center;
        }
        .navbar a {
            display: inline-block;
            color: #fff;
            padding: 14px 20px;
            text-decoration: none;
            font-size: 18px;
        }
        .navbar a:hover {
            background-color: #555;
        }
        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .section {
            display: none;
        }
        .active {
            display: block;
        }
        h1 {
            color: #333;
            text-align: center;
        }
        .contact-info, .gallery, .videos {
            list-style-type: none;
            padding: 0;
            text-align: center;
        }
        .contact-info li, .gallery li {
            margin: 10px 0;
            font-size: 18px;
            color: #555;
        }
        .contact-info li span {
            font-weight: bold;
        }
        .gallery img {
            max-width: 100%;
            height: auto;
            margin: 5px;
        }
        .videos iframe {
            width: 100%;
            height: 315px;
            margin: 10px 0;
        }
    </style>
    <script>
        function showSection(sectionId) {
            const sections = document.getElementsByClassName('section');
            for (let i = 0; i < sections.length; i++) {
                sections[i].classList.remove('active');
            }
            document.getElementById(sectionId).classList.add('active');
        }
    </script>
</head>
<body>
    <div class="navbar">
        <a href="javascript:void(0)" onclick="showSection('home')">Home</a>
        <a href="javascript:void(0)" onclick="showSection('contact-info')">Contact Info</a>
        <a href="javascript:void(0)" onclick="showSection('gallery')">Gallery</a>
        <a href="javascript:void(0)" onclick="showSection('videos')">Videos</a>
    </div>

    <div class="container">
        <div id="home" class="section active">
            <h1>Welcome to Our Church</h1>
            <p>This is the official webpage for our church. Learn more about our community, service times, and upcoming events.</p>
        </div>

        <div id="contact-info" class="section">
            <h1>Contact Information</h1>
            <ul class="contact-info">
                <li><span>Address:</span> 2846 Lebanon Pike, Nashville, TN 37214</li>
                <li><span>Service Area:</span> Nashville, TN</li>
                <li><span>Mobile:</span> (615) 927-4808</li>
                <li><span>Email:</span> <a href="mailto:2017neec@gmail.com">2017neec@gmail.com</a></li>
            </ul>
        </div>

        <div id="gallery" class="section">
            <h1>Church Gallery</h1>
            <ul class="gallery">
                <li><img src="church_photo1.jpg" alt="Church Service 1"></li>
                <li><img src="church_photo2.jpg" alt="Church Service 2"></li>
                <li><img src="church_photo3.jpg" alt="Community Event"></li>
                <!-- Add more photos as needed -->
            </ul>
        </div>

        <div id="videos" class="section">
            <h1>Church Videos</h1>
            <p>Watch our recent sermons and messages on YouTube:</p>
            <div class="videos">
                <iframe src="https://www.youtube.com/embed/VIDEO_ID_1" frameborder="0" allowfullscreen></iframe>
                <iframe src="https://www.youtube.com/embed/VIDEO_ID_2" frameborder="0" allowfullscreen></iframe>
                <!-- Add more video links as needed -->
            </div>
        </div>
    </div>
</body>
</html>
name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
